require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  ExtraDetails: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0.0
  Exclude:
    - bin/**/*
    - node_modules/**/*
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - config/environments/production.rb




Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/RescueStandardError:
  EnforcedStyle: implicit
